### ISSUE TITLE
Other non-standalone specs mixed in the job that initialize by `@distribute --standalone` 

### ISSUE THREAD

**Issue by wuhuizuo** [sangfor-vtt/tes-request#6]
## 问题
有些情况下其它不要求独立分发(没有@distribute --standalone标记)的spec脚本会混入到期望单个脚本独立运行的任务中

## 重现步骤
如果项目的`.ci.yml` 存在如下任务项:

```yml
distribute_limit:
  spec:
    pattern:
    - spec/distribute_limit/standalone_spec.rb
    - spec/distribute_limit/common_spec.rb
```
其中2个脚本文件的环境要求相同,只是 `standalone_spec.rb`多了分发的要求:
```ruby
# @env begin
# ...
# @distribute --standalone
# @end
```

## 备注
需要`Tes::Request::RSpec::Distribute#gen_pieces` 中fix这个问题.
